version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: paperless-postgres
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: test
      POSTGRES_PASSWORD: paper
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d paperless"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paperless-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paperless
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: paper
    depends_on:
      - postgres
    # Kein volumes-Mount, damit das kopierte JAR nicht überschrieben wird

volumes:
  pgdata:
