spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/paperless
    username: test
    password: paper
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8081

#ToDo Paths einfügen
#Beim Curl ist es mir aber ein Rätsel