spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/paperless
    username: test
    password: paper
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:user}
    password: ${SPRING_RABBITMQ_PASSWORD:pass}

server:
  port: 8081

#ToDo Paths einfügen
#Beim Curl ist es mir aber ein Rätsel